- name: Scales the deployment down to 0
  hosts: all
  collections: 
    - kubernetes.core
  tasks:
     - name: debug the variables
       ansible.builtin.debug:
         var: ansible_eda
         
     - name: Scale down the deployment to 0
       kubernetes.core.k8s:
         api_key: sha256~IoD-SLPVNORLdm-8PWOhxMtpi1LWE3wgxaPT-kIIr5U
         host: https://api.rosa-kpmjr.85x6.p1.openshiftapps.com:6443
         validate_certs: false
         state: absent
         kind: Deployment
         namespace: "{{ ansible_eda.event.body.namespace }}"
         name: "{{ ansible_eda.event.body.deployment }}"
