- name: Scales the deployment down to 0
  hosts: all
  collections: 
    - kubernetes.core
  tasks:
     - name: debug the variables
       ansible.builtin.debug:
         var: ansible_eda
         
     - name: Scale down the deployment to 0
       kubernetes.core.k8s:
#         api_key: sha256~DJ8cuKYHwLiVnV4J-XHWgcs_fP8DgQJNVKZyXAC3kWc
#         host: https://api.rosa-vtcdb.wvqh.p1.openshiftapps.com:6443
         api_key: "{{ api_key }}"
         host: "{{ host }}"
         validate_certs: false
         state: absent
         kind: Deployment
         namespace: "{{ ansible_eda.event.body.namespace }}"
         name: "{{ ansible_eda.event.body.deployment }}"
