- name: Initiate Forensic activities on target PoD
  hosts: all
  collections: 
    - kubernetes.core
  tasks:
     - name: Retrieve the PoDs in the namespace
       kubernetes.core.k8s_info:
         api_key: sha256~A-9QiEhqQdtbaLc3kHweVYSlGFZ4WVmIAAIGIgYwc0A
         host: https://api.simon-aws.hbbq.p1.openshiftapps.com:6443
         kind: Pod
         namespace: simon-test-3
       register: pod_list
        
#     - name: see the list
#       ansible.builtin.debug:
#         var: pod_list

     - name: see the PoD name(s)
       ansible.builtin.debug:
         var: pod_list.resources[0].metadata.name

    
     - name: Mark the selected PoD with the relevant Label
       kubernetes.core.k8s:
         api_key: sha256~A-9QiEhqQdtbaLc3kHweVYSlGFZ4WVmIAAIGIgYwc0A
         host: https://api.simon-aws.hbbq.p1.openshiftapps.com:6443
         state: patched
         kind: Pod
         namespace: simon-test-3
         name: "{{ pod_list.resources[0].metadata.name }}"
#         label_selectors:
#           - app = hello-simon
         definition:
           metadata:
             labels: 
               contained: red
 
