- name: Initiate Forensic activities on target PoD
  hosts: all
  collections: 
    - kubernetes.core
  tasks:
     - name: Retrieve the PoDs in the namespace
       kubernetes.core.k8s_info:
         api_key: sha256~w035QrYq-SRKvzz5fkfYq1YAHyEZEH0kmDbvPS4Zj4k
         host: https://api.df2jcu0i.westeurope.aroapp.io:6443
         kind: Pod
         namespace: simon-test-3
       register: pod_list
        
#     - name: see the list
#       ansible.builtin.debug:
#         var: pod_list

     - name: see the PoD name(s)
       ansible.builtin.debug:
         var: pod_list.resources.kind
