- name: Initiate Forensic activities on target PoD
  hosts: all
  collections: 
    - kubernetes.core
  tasks:
     - name: Mark the selected PoD with the relevant Label
       kubernetes.core.k8s:
         api_key: sha256~w035QrYq-SRKvzz5fkfYq1YAHyEZEH0kmDbvPS4Zj4k
         host: https://api.df2jcu0i.westeurope.aroapp.io:6443
         state: patched
         kind: Pod
         namespace: simon-test-3
         name: router-melbourne-
         definition:
           metadata:
             labels: 
               contained: red
 
     - name: Retrieve the content from the PoD 
       pause:
         seconds: 10

#     - name: Publish to Kafka router-a has come online
#       uri:
#         url: 'http://my-bridge-bridge-service-my-kafka-project.apps.rosa-mfhlq.6ns1.p1.openshiftapps.com/topics/my-topic'
#         method: POST
#         body: '{"records": [ {"key":"my-key","value": "endpoint-a is now configured" }]}'
#         headers:
#           content-type: application/vnd.kafka.json.v2+json        

     - name: Do something beautiful
       pause:
         seconds: 10
