-
  name: 'http://my-bridge-bridge-service-my-kafka-project.apps.rosa-mfhlq.6ns1.p1.openshiftapps.com/topics/my-topic'
  uri:
    url: 'http://my-bridge-bridge-service-my-kafka-project.apps.rosa-mfhlq.6ns1.p1.openshiftapps.com/topics/my-topic'
    method: POST
    body: '{"records": [ {"key":"my-key","value": "cisco is now configured" }]}'
    headers:
      content-type: application/vnd.kafka.json.v2+json
  register: result
