#- name: Log into OpenShift
#  hosts: all
#  module_defaults:
#    group/k8s:
#  tasks:
#     - name: Log in (obtain access token)
#       k8s_auth:
#         username: admin
#         password: id8cj-ru2s3-W4pa5-Qfrqo
#         host: https://api.rosa-mfhlq.6ns1.p1.openshiftapps.com:6443
#       register: k8s_auth_results
#
#     - name: Get a list of all pods from any namespace
#       k8s_info:
#         api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
#         kind: Pod
#       register: pod_list

 
- name: Publish to Kafka
  hosts: all
  tasks:
     - name: allo allo
       uri:
         url: 'http://my-bridge-bridge-service-my-kafka-project.apps.rosa-mfhlq.6ns1.p1.openshiftapps.com/topics/my-topic'
         method: POST
         body: '{"records": [ {"key":"my-key","value": "cisco is now configured" }]}'
         headers:
           content-type: application/vnd.kafka.json.v2+json
