#- name: Log into OpenShift
#  hosts: all
#  module_defaults:
#    group/k8s:
#  tasks:
#     - name: Log in (obtain access token)
#       k8s_auth:
#         username: admin
#         password: id8cj-ru2s3-W4pa5-Qfrqo
#         host: https://api.rosa-mfhlq.6ns1.p1.openshiftapps.com:6443
#       register: k8s_auth_results
#
#     - name: Get a list of all pods from any namespace
#       k8s_info:
#         api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
#         kind: Pod
#       register: pod_list

 
- name: Log into OpenShift
  hosts: all
  vars:
     token: "sha256~LGkFF6SBZi_FeYy6HkrzJ9jy9siS3BbY7kXJiMpiPIc"
     cluster: "https://api.rosa-mfhlq.6ns1.p1.openshiftapps.com:6443"
  collections: 
    - kubernetes.core
#  plugin: kubernetes.core.k8s
  tasks:
     - name: debug message
       debug:
         msg: "allez les bleus"
         
     - name: do something else
       debug:
         msg: "allez les verts"
         
     - name: Create a Service object from an inline definition
       kubernetes.core.k8s:
         api_key: {{ token }}
         host: {{ cluster }}
         state: present
         definition:
           apiVersion: v1
           kind: Service
           metadata:
             name: web
             namespace: fuckoff
             labels:
               app: galaxy
               service: web
           spec:
             selector:
               app: galaxy
               service: web
             ports:
             - protocol: TCP
               targetPort: 8000
               name: port-8000-tcp
               port: 8000
   
     - name: Create the Melbourne
       kubernetes.core.k8s:
         api_key: {{ token }}
         host: {{ cluster }}
         definition:
           apiVersion: apps/v1
           kind: Deployment
           metadata:
             name: router-melbourne
             namespace: simple-vpn
           spec:
             replicas: 1
             selector:
               matchLabels:
                 app: router-melbourne
             template:
               metadata:
                 labels:
                   app: router-melbourne
               spec:
                 containers:
                 - name: router-melbourne
                   image: paulbouwer/hello-kubernetes:1.8
                   ports:
                   - containerPort: 8080
   
     - name: Create the Sydney
       kubernetes.core.k8s:
         api_key: {{ token }}
         host: {{ cluster }}
         definition:
           apiVersion: apps/v1
           kind: Deployment
           metadata:
             name: router-sydney
             namespace: simple-vpn
           spec:
             replicas: 1
             selector:
               matchLabels:
                 app: router-sydney
             template:
               metadata:
                 labels:
                   app: router-sydney
               spec:
                 containers:
                 - name: router-sydney
                   image: paulbouwer/hello-kubernetes:1.8
                   ports:
                   - containerPort: 8080
   
   
   
         
#     - name: connect to openshift
#       kubernetes.core.k8s_auth:
#         username: cluster-admin
#         password: id8cj-ru2s3-W4pa5-Qfrqo
#         host: https://api.rosa-mfhlq.6ns1.p1.openshiftapps.com:6443
#       register: k8s_auth_results


