- name: Log into OpenShift
#  hosts: all
#  tasks:
#    - name: log into openshift
#    k8s_auth:  
#      username: cluster-admin
#      password: id8cj-ru2s3-W4pa5-Qfrqo
#      host: https://api.rosa-mfhlq.6ns1.p1.openshiftapps.com:6443
#      validate_certs: true 
#    register: k8s_auth_results

- hosts: localhost
  module_defaults:
    group/k8s:
#     host: https://api.rosa-mfhlq.6ns1.p1.openshiftapps.com/
#      ca_cert: ca.pem
  tasks:
#  - block:
    # It's good practice to store login credentials in a secure vault and not
    # directly in playbooks.
#    - include_vars: k8s_passwords.yml

    - name: Log in (obtain access token)
      k8s_auth:
        username: admin
        password: id8cj-ru2s3-W4pa5-Qfrqo
        host: https://api.rosa-mfhlq.6ns1.p1.openshiftapps.com:6443
        register: k8s_auth_results

    # Previous task provides the token/api_key, while all other parameters
    # are taken from module_defaults
    - name: Get a list of all pods from any namespace
      k8s_info:
        api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
        kind: Pod
      register: pod_list

 
