
- name: Log into OpenShift
  hosts: all
#  vars:
#     token: "sha256~LGkFF6SBZi_FeYy6HkrzJ9jy9siS3BbY7kXJiMpiPIc"
#     cluster: "https://api.rosa-mfhlq.6ns1.p1.openshiftapps.com:6443"
  collections: 
    - kubernetes.core
  tasks:
     - name: debug message
       debug:
         msg: "checking it is ok"
         
     - name: do something else
       debug:
         msg: "it is ok"
        
   
     - name: Create the endpoint-a Router
       kubernetes.core.k8s:
         api_key: sha256~LGkFF6SBZi_FeYy6HkrzJ9jy9siS3BbY7kXJiMpiPIc
         host: https://api.rosa-mfhlq.6ns1.p1.openshiftapps.com:6443
         definition:
           apiVersion: apps/v1
           kind: Deployment
           metadata:
             name: router-melbourne
             namespace: simple-vpn
           spec:
             replicas: 1
             selector:
               matchLabels:
                 app: router-melbourne
             template:
               metadata:
                 labels:
                   app: router-melbourne
               spec:
                 containers:
                 - name: router-melbourne
                   image: paulbouwer/hello-kubernetes:1.8
                   ports:
                   - containerPort: 8080
   
     - name: Create the endpoint-b router
       kubernetes.core.k8s:
         api_key: sha256~LGkFF6SBZi_FeYy6HkrzJ9jy9siS3BbY7kXJiMpiPIc
         host: https://api.rosa-mfhlq.6ns1.p1.openshiftapps.com:6443
         definition:
           apiVersion: apps/v1
           kind: Deployment
           metadata:
             name: router-sydney
             namespace: simple-vpn
           spec:
             replicas: 1
             selector:
               matchLabels:
                 app: router-sydney
             template:
               metadata:
                 labels:
                   app: router-sydney
               spec:
                 containers:
                 - name: router-sydney
                   image: paulbouwer/hello-kubernetes:1.8
                   ports:
                   - containerPort: 8080
   
 
     - name: Publish to Kafka the result
       uri:
         url: 'http://my-bridge-bridge-service-my-kafka-project.apps.rosa-mfhlq.6ns1.p1.openshiftapps.com/topics/my-topic'
         method: POST
         body: '{"records": [ {"key":"my-key","value": "service is now configured" }]}'
         headers:
           content-type: application/vnd.kafka.json.v2+json
   
   
