apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"policy.open-cluster-management.io/v1","kind":"Policy","metadata":{"annotations":{"policy.open-cluster-management.io/categories":"Operators-Install","policy.open-cluster-management.io/controls":"AAP-Operator","policy.open-cluster-management.io/standards":"ACME-Standards"},"name":"policy-aap-operator","namespace":"default"},"spec":{"disabled":false,"policy-templates":[{"objectDefinition":{"apiVersion":"policy.open-cluster-management.io/v1","kind":"ConfigurationPolicy","metadata":{"name":"aap-operator-ns"},"spec":{"object-templates":[{"complianceType":"musthave","objectDefinition":{"apiVersion":"v1","kind":"Namespace","metadata":{"name":"aap"}}}],"remediationAction":"enforce","severity":"high"}}},{"objectDefinition":{"apiVersion":"policy.open-cluster-management.io/v1","kind":"ConfigurationPolicy","metadata":{"name":"aap-operator-operator-group"},"spec":{"object-templates":[{"complianceType":"musthave","objectDefinition":{"apiVersion":"operators.coreos.com/v1","kind":"OperatorGroup","metadata":{"name":"ansible-aautomation-platform-operator","namespace":"aap"},"spec":null}}],"remediationAction":"enforce","severity":"high"}}},{"objectDefinition":{"apiVersion":"policy.open-cluster-management.io/v1","kind":"ConfigurationPolicy","metadata":{"name":"aap-operator-subscription"},"spec":{"object-templates":[{"complianceType":"musthave","objectDefinition":{"apiVersion":"operators.coreos.com/v1alpha1","kind":"Subscription","metadata":{"name":"ansible-aautomation-platform-operator","namespace":"aap"},"spec":{"installPlanApproval":"Automatic","name":"ansible-automation-platform-operator","source":"redhat-operators","sourceNamespace":"openshift-marketplace"}}}],"remediationAction":"enforce","severity":"high"}}}],"remediationAction":"enforce"}}
    policy.open-cluster-management.io/categories: Operators-Install
    policy.open-cluster-management.io/controls: AAP-Operator
    policy.open-cluster-management.io/standards: ACME-Standards
  name: default.policy-aap-operator
  namespace: local-cluster
  labels:
    policy.open-cluster-management.io/cluster-name: local-cluster
    policy.open-cluster-management.io/cluster-namespace: local-cluster
    policy.open-cluster-management.io/root-policy: default.policy-aap-operator
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: aap-operator-ns
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: aap
          remediationAction: enforce
          severity: high
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: aap-operator-operator-group
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1
                kind: OperatorGroup
                metadata:
                  name: ansible-aautomation-platform-operator
                  namespace: aap
                spec: null
          remediationAction: enforce
          severity: high
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: aap-operator-subscription
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: Subscription
                metadata:
                  name: ansible-aautomation-platform-operator
                  namespace: aap
                spec:
                  installPlanApproval: Automatic
                  name: ansible-automation-platform-operator
                  source: redhat-operators
                  sourceNamespace: openshift-marketplace
          remediationAction: enforce
          severity: high
  remediationAction: enforce
